export const refs = {
  body: document.querySelector("body"),
  formSection: document.querySelector(".form-section"),
  form: document.querySelector(".form"),
  heroSection: document.querySelector(".hero-section"),
  hero: document.querySelector(".hero-container"),
  heroImage: document.querySelector(".hero-img"),
  heroName: document.querySelector(".hero-name"),
  infoScore: document.querySelector("#info-score"),
  infoAllClick: document.querySelector("#info-clicks"),
  infoName: document.querySelector("#info-name"),
  enemyHp: document.querySelector("#enemy-hp"),
  yourHp: document.querySelector("#your-hp"),
  backdrop: document.querySelector(".backdrop"),
  levelModalText: document.querySelector(".level-text"),
  modalBtnLevel: document.querySelector("#next-level"),
  modalLevel: document.querySelector(".modal-level"),
  modalLose: document.querySelector(".modal-lose"),
  modalFinish: document.querySelector(".modal-finish"),
  modalBtnRestart: document.querySelector("#finish-restart"),
  modalBtnRestartLose: document.querySelector("#lose-restart"),
  modalBtnChange: document.querySelector("#finish-change"),
  listHero: document.querySelector(".list-hero"),
};
