export const heroes = [
  {
    id: 1,
    nameHero: "Colt",
    hp: 10,
    level: { name: "easy", color: "#32c12c" },
    img: "../images/heroes/colt.png",
    bgc: "../images/background/blue.jpg",
  },
  {
    id: 2,
    nameHero: "Pocco",
    hp: 20,
    level: { name: "medium", color: "#ff9a00" },
    img: "../images/heroes/pocco.png",
    bgc: "../images/background/green.png",
  },
  {
    id: 3,
    nameHero: "Shelly",
    hp: 30,
    level: { name: "hard", color: "#ff5500" },
    img: "../images/heroes/shelly.png",
    bgc: "../images/background/blue.jpg",
  },
  {
    id: 4,
    nameHero: "Spike",
    hp: 40,
    level: { name: "expert", color: "#7c5547" },
    img: "../images/heroes/spike.png",
    bgc: "../images/background/green.png",
  },
  {
    id: 5,
    nameHero: "Voron",
    hp: 50,
    level: { name: "pro", color: "#d40c00" },
    img: "../images/heroes/voron.png",
    bgc: "../images/background/blue.jpg",
  },
];
